### ISSUE TITLE
-l, -a, and -? together.

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/pawn#101]
It would be very useful for those of us who do strange things with pre-processor macros and assembly to be able to generate multiple code versions at once, e.g. pre-processed (-l), assembly (-a) and final (-something else) together, to look at what is going on at any moment.  As it is, I frequently have "pawn.cfg" open in a tab along with any code that I'm working on to constantly switch compile modes.  Currently, if there is neither "-l" nor "-a", a full ".amx" file is generated, but if you want that "as well" as other outputs, it will need a flag to specify this.  So I propose adding "-f" for "final", and making "-l", "-a", and "-f" composable so that one compile can generate up to three outputs - ".lst", ".asm", and ".amx".  Clearly the default behaviour should remain, so that specifying none of the flags will just create a ".amx".

Currently, ".asm" and ".amx" files are not generated if there are any syntax errors/warnings, while ".lst" files frequently are because most code structure has not yet been checked.  If there are errors with multiple filetype outputs, earlier stages should still be generated.  If fact, this is possibly the MOST useful feature of this addition, since then the generated ".lst" file can be compared to the errors it generates.

I have a feeling that this will not be hard to add at all, so I'll give it a go myself very soon.  If the code is in ay way sane, it is just a "stop compiling" call after generating one of the outputs, which needs more qualifications.

**Comment by JernejL** [comment]
y_less: listfile mode can be used with command line, that's way easier to switch than cfg file. 
 
pawncc.exe -;+ -(+ -l 
 
Infact you can use that as step 1 then feed the listfile directly into pawncc again and you'll get the amx as desired with ability to check what your preprocessor #defines have outputted just like you want.

**Comment by Y-Less** [comment]
Very true, I hadn't set up using the command line simply, but you're right that that's a better solution.  I'm not convinced that you can pipe .lst files back in - my understanding was that they had some bits in that couldn't be compiled (`#file`, `#line`, etc.), but I've written a script to do all three versions in parallel and I'll test the piping version.

**Comment by JernejL** [comment]
I use listfile for internal precompiler (which was its original purpose iirc) and am compiling listfile as input for past 7-8 years. 
Zeex fixed a few issues with listfile like "#file" paths (quotes problem), but it's certainly working very well, generated amx files are good and have no issues with debug symbols or anything else whatsoever.

**Comment by Y-Less** [comment]
OK then...
