### ISSUE TITLE
32 character limit for routine names

### ISSUE THREAD

**Issue by JernejL** [Southclaws/pawn#102]
Is it possible to extend the 32 character limit for routine names? simply as that, i am hitting length limit quite often lately :(

**Comment by Y-Less** [comment]
I assume you are aware of this, but should probably note anyway that the SA:MP server has the same restriction internally when looking up public functions by name.  So while normal functions could have the lengths extended, public functions can't - they will compile but not run.

**Comment by JernejL** [comment]
Not an issue at all. This is mostly a problem for internal functions only, not publics / stocks.

**Comment by Y-Less** [comment]
I don't use this syntax, and maybe you don't, but a lot of people do this:

```pawn
#define Player:: Player_

Player::Connect(pid)
{
}
```

I've seen one solution when someone did this for long names - there's no reason why the input and output should match closely:

```pawn
#define Player:: P@

Player::Connect(pid)
{
}
```

Same input, shorter output.

**Comment by JernejL** [comment]
I use nothing like that, i simply rename native functions and provide a replacement: 
 
native real_PlayerTextDrawSetPreviewModel(playerid, PlayerText:text, modelindex) = PlayerTextDrawSetPreviewModel;

then make a replacement stock with additional hooks inside:

stock PlayerTextDrawSetProportional(playerid, PlayerText:text, set) {

	return real_PlayerTextDrawSetProportio(playerid, PlayerText:text, set);

}

But then i have a too long name real_PlayerTextDrawSetPreviewModel which won't fit, so i have to get creative with shorter improvised names.

**Comment by ziggi** [comment]
@JernejL just use [recommendations](https://github.com/Open-GTO/sa-mp-fixes/blob/master/fixes.inc#L738-L745) by Y_Less about these names:
```
 * Certain terms may be shortened when dealing with long callback names to avoid
 *     compile truncation warnings (max symbol length is 31).  Current list:
 *
 *         "Checkpoint" -> "CP"
 *         "Update"     -> "Upd"
 *         "TextDraw"   -> "TD"
 *         "Object"     -> "Obj"
 *         "Player"     -> "P"
```

**Comment by JernejL** [comment]
ofcourse i'm working a workaround, but a fix would still be helpful :)

**Comment by kurta999** [comment]
I don't want to create new issue for this:

It's possible to increase maximum acceptable argument lenght? I would like to add an "auto compile" option for my map converter, but I can't do it because if path of compilable .pwn is very long, it won't work. For some reason pwncc will truncate it.

	char szLocation[MAX_PATH];
	char szCommandLine[MAX_PATH * 3];
	GetCurrentDirectory(MAX_PATH, szLocation);
	
	sprintf(szCommandLine, ".\\pawno\\pawncc.exe %s\\scriptfiles\\maps\\SAMP\\%s.pwn", szLocation, map->second->mapName.c_str());

This doesn't work if path is too long.

**Comment by YashasSamaga** [comment]
MAX_PATH is defined by the standard library implementation.

This cannot be fixed without hacks (using winapi & linuxapi).

**Comment by JernejL** [comment]
http://stackoverflow.com/questions/27680647/does-max-path-issue-still-exists-in-windows-10
 
see: 
 
"Windows 10 (Version 1607 - Anniversary Update) and Windows Server 2016 you seam to have an option to ignore the MAX_PATH issue" 
 
This is likely your problem and solution.

**Comment by kurta999** [comment]
Thanks!
