### ISSUE TITLE
returning arrays of unknown size

### ISSUE THREAD

**Issue by YashasSamaga** [Southclaws/pawn#154]
`func(arr[])
{
     return arr;
}`

`printf("test %s", func("Abc");`

prints the output as test ,@

The reason is
```
proc	; func
break	; c
load.s.pri c
load.s.alt 10
movs 0 ; zero!
retn
```

**Comment by Dayvison** [comment]
#161 on linux assertion fails

**Comment by YashasSamaga** [comment]
`Assertion failed: retsize>0, file E:\SAMP\PAWN Compiler\Zeex\pawn-3.10.2\source\compiler\sc3.c, line 1986`

**Comment by Dayvison** [comment]
Well i don't try this on windows, but many issues i open the assertions only failed on linux #162 ^.^ sorry

**Comment by YashasSamaga** [comment]
@Southclaws close?
