### ISSUE TITLE
#define not working properly

### ISSUE THREAD

**Issue by rt-2** [Southclaws/pawn#163]
Hello,
I have had this issue, not sure if related to this compiler but maybe :
file 1:
```
#define WEAPON_UNKNOWN 55
```
file 2:
```
[Using WEAPON_UNKNOWN]
```
file 3 includes both files and I get this error
```
../include/file2.pwn(282) : error 017: undefined symbol "WEAPON_UNKNOWN"
```
File 1 is actually weapon-config.inc, and i'm trying to use the constant WEAPON_UNKNOWN in another script that is included AFTER weapon-config.inc
But normally this is supposed to work, I had some instance of this happening with functions too.
This is very annoying.

rt-2

**Comment by Y-Less** [comment]
Does file 2 include file 3?  If you have circular dependencies you can end up with includes being done in orders you might not expect and so give strange errors.

**Comment by rt-2** [comment]
No, file 3 is my gamemode, both file1 and file2 are included in it,
I am not able to reproduce this bug in a blank gamemode so i will do some investigations on my side, but I think it happened to me before randomly also but with a function.
