### ISSUE TITLE
Crash compiler

### ISSUE THREAD

**Issue by continue98** [Southclaws/pawn#178]
Hi. I am updated compiler to 3.10.1 and compiler began crashed. i used compiler version 3.2.3664 and compiler not crashed. 
Exception number code: c0000005
Module name with error: PAWNC.dll
Application timestamp: 589582de
Version application: 3.10.0.0
Version OS: Windows 7 (6.1.7601.2.1.0.256.1)
Offset exception: 0001f4e0

What is the problem?

P.S: I apology for bad know English lang.
P.S:S Zeex, you are from Russia?

**Comment by continue98** [comment]
Oops, i am forgot re update dc kickfix. (bug in #emit. commit by VVVVV)

**Comment by YashasSamaga** [comment]
@Southclaws close?
