### ISSUE TITLE
Invalid memory access

### ISSUE THREAD

**Issue by Romz24** [Southclaws/pawn#194]
Hello! I propose to add a warping if someone tries to go beyond the array through a format, is this possible? I accidentally did this, then I was looking for a long time why the third-party variables overwritten the data. I could not understand the reason for the random falls.

Code: http://forum.sa-mp.com/showpost.php?p=3939932&postcount=15409

**Comment by Y-Less** [comment]
This is mainly for the compiler, that's got nothing to do with this.  Plus, that's not possible anywhere, since what is to simply stop people giving `format` the wrong array size?

**Comment by Romz24** [comment]
Why not add a warning to the compiler if someone goes beyond the array in the format?
If this array is global and someone refers to it through a format and specifies a long length, there will be crashes that are difficult to catch because the crashdetect plugin will throw an error on third-party strings.

Sorry for my bad english.

**Comment by Y-Less** [comment]
Again, that is not possible, and format is not part of the compiler.

**Comment by Romz24** [comment]
Very sorry.

**Comment by Y-Less** [comment]
What's more, you shouldn't really ever be going OOB, if you just do `format(x, sizeof (x), "format string", params);` - it does have internal checking.

**Comment by YashasSamaga** [comment]
@Southclaws close?
