### ISSUE TITLE
Weird...

### ISSUE THREAD

**Issue by NemanjaMAX** [Southclaws/pawn#197]
All worked with older compiler, until i updated pawn...

Errors:
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\a_http.inc(22) : error 021: symbol already defined: "HTTP"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(95) : error 021: symbol already defined: "YSI_g_sScriptInitGM"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(96) : error 021: symbol already defined: "YSI_g_sScriptExitGM"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(110) : warning 209: function "ScriptInit_OnFilterScriptInit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(131) : warning 209: function "ScriptInit_OnGameModeInit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(178) : warning 209: function "ScriptInit_OnFilterScriptExit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(196) : warning 209: function "ScriptInit_OnGameModeExit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(216) : warning 201: redefinition of constant/macro (symbol "OnScriptInit")
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(237) : error 084: state conflict: one of the states is already assigned to another implementation (symbol "_ScriptInit_FixState")
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(241) : error 084: state conflict: one of the states is already assigned to another implementation (symbol "_ScriptInit_FixState")
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\internal\y_version.inc(133) : error 021: symbol already defined: "ScriptInit_OnScriptInit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\a_http.inc(22) : error 021: symbol already defined: "HTTP"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(95) : error 021: symbol already defined: "YSI_g_sScriptInitGM"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(96) : error 021: symbol already defined: "YSI_g_sScriptExitGM"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(99) : error 021: symbol already defined: "ScriptInit_OnFilterScriptInit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(110) : warning 209: function "ScriptInit_OnFilterScriptInit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(113) : error 021: symbol already defined: "ScriptInit_OnGameModeInit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(131) : warning 209: function "ScriptInit_OnGameModeInit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(170) : error 021: symbol already defined: "ScriptInit_OnFilterScriptExit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(178) : warning 209: function "ScriptInit_OnFilterScriptExit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(181) : error 021: symbol already defined: "ScriptInit_OnGameModeExit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(196) : warning 209: function "ScriptInit_OnGameModeExit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(216) : warning 201: redefinition of constant/macro (symbol "OnScriptInit")
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(237) : error 084: state conflict: one of the states is already assigned to another implementation (symbol "_ScriptInit_FixState")
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(241) : error 084: state conflict: one of the states is already assigned to another implementation (symbol "_ScriptInit_FixState")
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\internal\y_version.inc(133) : error 021: symbol already defined: "ScriptInit_OnScriptInit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(95) : error 021: symbol already defined: "YSI_g_sScriptInitGM"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(96) : error 021: symbol already defined: "YSI_g_sScriptExitGM"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(99) : error 021: symbol already defined: "ScriptInit_OnFilterScriptInit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(110) : warning 209: function "ScriptInit_OnFilterScriptInit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(113) : error 021: symbol already defined: "ScriptInit_OnGameModeInit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(131) : warning 209: function "ScriptInit_OnGameModeInit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(170) : error 021: symbol already defined: "ScriptInit_OnFilterScriptExit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(178) : warning 209: function "ScriptInit_OnFilterScriptExit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(181) : error 021: symbol already defined: "ScriptInit_OnGameModeExit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(196) : warning 209: function "ScriptInit_OnGameModeExit" should return a value
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(216) : warning 201: redefinition of constant/macro (symbol "OnScriptInit")
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(237) : error 084: state conflict: one of the states is already assigned to another implementation (symbol "_ScriptInit_FixState")
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_scriptinit.inc(241) : error 084: state conflict: one of the states is already assigned to another implementation (symbol "_ScriptInit_FixState")
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\YSI\y_debug.inc(352) : error 021: symbol already defined: "ScriptInit_OnScriptInit"
C:\Users\iwanmf\Desktop\AG-RP\pawno\include\a_http.inc(22) : error 021: symbol already defined: "HTTP"

**Comment by Y-Less** [comment]
You are using a very old version of YSI.

**Comment by NemanjaMAX** [comment]
But when i update it spam errors..

**Comment by justnonamenoname** [comment]
compat=1
