### ISSUE TITLE
`YSI\internal\..\internal\y_natives.inc(65) : fatal error 100: cannot read from file: "y_globaltags"`

### ISSUE THREAD

**Issue by NemanjaMAX** [Southclaws/pawn#214]
Help please :)

\NiceTRY\pawno\include\YSI\internal\..\internal\y_natives.inc(65) : fatal error 100: cannot read from file: "y_globaltags"

Compilation aborted.

Pawn compiler 3.10.4	 	 	Copyright (c) 1997-2006, ITB CompuPhase

1 Error.

**Comment by Y-Less** [comment]
Do you have the latest version of YSI?  y_globaltags is there and I know it compiles with this compiler.

**Comment by Y-Less** [comment]
Just close this. It should be in the YSI repository anyway.
