### ISSUE TITLE
[suggestion] New constant

### ISSUE THREAD

**Issue by Romz24** [Southclaws/pawn#218]
I suggest adding a new constant, which will determine the name of the running filterscript or gamemode.

What is it for:
1. With this, you can easily reload the script even if it is renamed.
> new command[16];
> format(command, sizeof(command), "reloadfs %s", __scriptname);
> SendRconCommand(command);

2. You can make protection from changing the name of the filterscript or gamemode.
>if(strcmp("myname", __scriptname) != 0)
>{
>  new command[16];
>  format(command, sizeof(command), "unloadfs %s", __scriptname);
>  SendRconCommand(command);
>}

**Comment by Dayvison** [comment]
Não iria adiantar, já que apos compilado você poderia renomear o .amx ou .pwn

**Comment by Naseband** [comment]
How would this protection work? The constant wouldn't change if I rename the .amx file after compiling it.

**Comment by Y-Less** [comment]
> The constant wouldn't change if I rename the .amx file after compiling it.

And if it did change - then how is it "constant"?

**Comment by YashasSamaga** [comment]
There is `__file` which gives the name of the script "being processed". If used in a include, it would give the name of the include file.

It is not possible for the compiler to provide a mechanism to determine the file name at runtime.

@Southclaws close?
