### ISSUE TITLE
[FEATURE REQUEST] #pragma align may accept a value

### ISSUE THREAD

**Issue by YashasSamaga** [Southclaws/pawn#219]
The PAWN Language Guide says the following:

> Aligns the next declaration to the oﬀset set with the alignment compiler option. Some (native) functions may perform better with parameters that are passed by reference when these are on boundaries of 8, 16, or even 32 bytes. Alignment requirements are dependent of the host applications.

Using `#pragma align 16` gives `error 038: extra characters on line`.

My suggestion is to allow the directive to *optionally* take a value. It should align the declaration which immediately follows to the mentioned byte-boundary.

## What's the use?

Suppose a plugin uses a 16 array (enum array?) in PAWN script. If the plugin is going to use a pointer to a user-defined type (say `struct pawnData;`) within its code to access the PAWN array, then it is a requirement of the C++ compiler that the pointer to `pawnData` meets the alignment requirements of the type. If the pointer points to a PAWN array which has a physical address in the memory which does not meet the alignment requirements for the type, accessing the object would cause undefined behavior. Compiler specific attributes can be used request the compiler to use instructions for misaligned access but this will be costly.

This directive might have the potential to set the necessary alignment in the PAWN code itself.

The other way round would be to use a regular cell array in the plugin which is not as pleasing as using a user defined data type.

## Red flags

Even if `#pragma align 16` is used, the final alignment depends on what boundary the AMX program's data section is loaded. If the data section was loaded on an 8-byte boundary at an odd multiple of 8, then the pragma align would fail to get the pawn array aligned to a physical 16-byte boundary which I think would render the align directive pointless.

The implementer guide mentions the following:
> The P-code follows the preﬁx immediately, but note that the preﬁx may be padded in order to align the code and data sections (this is a compiler option). The cod ﬁeld in the header is the ﬁle oﬀset to the start of the P-code

I wasn't able to find that compiler option in the language guide nor in the implementer guide.

**Comment by Y-Less** [comment]
Generally structs use the alignment of their largest member as their overall alignment, but if you are using the struct to represent data from PAWN, surely this will always be `sizeof (cell)`, in which case the alignments will already match.  Or do you have a use-case where this is not the case?

However, while that specific use-case is inaccurate, I'm sure there are other useful cases for this.

Side note, "must optionally" in RFCs is generally written as "may", saying something must optionally do something is a very odd turn of phrase.

**Comment by YashasSamaga** [comment]
I have a `struct` which stores two long doubles and a cell. I am trying to encode the object in a PAWN array because they get destroyed automatically.

**Comment by Y-Less** [comment]
What get destroyed?

**Comment by YashasSamaga** [comment]
When a user creates a object, I use defines to create an array of cells. The user tries to initialize it using a native. The plugin uses placement new operator to create the object in that array.

**Comment by Zeex** [comment]
Your object will not be destroyed automatically when the array holding it goes out of scope in Pawn, at least not in the C++ sense of destruction (where destructors are called). So, for example, if you allocate memory for some member variables and free it in the destructor you will get memory leaks because the destructor will never be called.

Regarding the alignment issue - can you give a real example where this is a problem? This sounds more like something that plugin authors should take care of, not the compiler. Also, how would you enforce this for people that use the standard compiler?

**Comment by YashasSamaga** [comment]
I don't use the destructive for the same reason. I just wanted the POD object to get freed when it goes out of scope in a PAWN script.

And yes,  the plugin should not depend on the compiler.

It was just bad design of the plugin and my craze to automate everything.
