### ISSUE TITLE
Multiple large initialised globals crash in the wrong order

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/pawn#220]
Crashes:

```pawn
new a[1000][500] = { { 0, 1, ... }, ... };
new b[500][2000] = { { 0, 1, ... }, ... };
```

Doesn't crash:

```pawn
new b[500][2000] = { { 0, 1, ... }, ... };
new a[1000][500] = { { 0, 1, ... }, ... };
```

I'm guessing it has something to do with allocating memory, since the crash doesn't happen if the total size of the second array is <= the first.

**Comment by YashasSamaga** [comment]
https://image.prntscr.com/image/TTe7rjEESRC-jSBUMzp4FA.png

I can't understand why that's even happening but there's the problem.

**Comment by YashasSamaga** [comment]
Replaced the pointers with indexes and it's working.

https://github.com/YashasSamaga/pawn/commit/538954b48345c7635576bfb0e724791de7f07c2d
