### ISSUE TITLE
Semicolon in a macro ignored

### ISSUE THREAD

**Issue by Dayvison** [Southclaws/pawn#223]
- Code
```pawn
#define test:%1+$ %1$
test:test+
test:test+$

#define test:%1+; %1;
test:test+
test:test+;

#define test:%1+! %1!
test:test+
test:test+!

#define test:%1+@ %1@
test:test+
test:test+@

```

- Output
```
test:test+
test$
test;test;;
test:test+
test!
test:test+
test@
```

**Comment by YashasSamaga** [comment]
Excerpt from the PAWN Language Guide (_The Preprocessor, Page 95_):

> If semicolons are optional at the end of each statement, the semicolon will also match a newline in the source.

Your output is the correct output for optional semicolons. If you force semicolons, you will get the 
correct output.

**With semicolon**:
```
#pragma semicolon true

#define test:%1+; %1;
test:test+
test:test+;
```

gives

```
#pragma semicolon true

#line 4
test:test+
test;

```

**Without semicolon:**
```
#pragma semicolon false

#define test:%1+; %1;
test:test+
test:test+;
```

gives

```
#pragma semicolon false

#line 4
test;test;;
```
