### ISSUE TITLE
Backslash immediately after first section of macro causes silent omission in v3.10.6

### ISSUE THREAD

**Issue by SinnerAssist** [Southclaws/pawn#226]
I downloaded this version and I can't use this anymore, I get: error 017: undefined symbol "AHCheck"
![image](https://user-images.githubusercontent.com/25451691/34499607-7b74b788-f00f-11e7-91a6-1c2cefd9cdb5.png)

**Comment by SinnerAssist** [comment]
It seems that if I move "do{" on the first line with the #define AHCheck() it's fixing the issue. So the first "\" it's the problem.

**Comment by YashasSamaga** [comment]
Removing the space between `)` and `\` fixes it., i.e: `#define AHCheck(%0,%1,%2)\` stops the error.

**Comment by Dayvison** [comment]
Nothing wrong here

**Comment by Southclaws** [comment]
We're investigating and it seems like there is actually something wrong.

**Comment by YashasSamaga** [comment]
The compiler concatenates the multiple lines before processing. The compiler marks the multi-line character with `\a`. In https://github.com/Southclaws/pawn/commit/693591bdc3491133f2aa90498c4ad8d3aadd0eb7 , a patch was added to prevent `\a` from being displayed in error/warning messages. That patch removed all `\a` from the line which actually combined which caused the following side effects:

```#define F\
      Hi
```

to be treated as

`#define FHi`

**Comment by Southclaws** [comment]
Needs confirmation.

**Comment by YashasSamaga** [comment]
How about closing this and reopening #191? This issue has been resolved but the issue #191 is back.

**Comment by Zeex** [comment]
I think I might have fixed line continuation bugs in https://github.com/Southclaws/pawn/commit/c325ca3e028388ae6f934df2a4057229d24d021e - it's simpler now and there is no insertion of `\a` anymore n because `\\` is allowed in comments (also added a test).
