### ISSUE TITLE
#endscript confusing

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/pawn#231]
So I was looking for something entirely unrelated in pawn-lang and found there is a `#endscript` directive I never knew about.  I tested it, then confirmed via [history.txt](https://github.com/Southclaws/pawn/blob/a0f4a4dce8ad124cdb6fbe0da61663a6a693d1a1/history.txt) that it is actually just a synonym for `#endinput`.  The two to me would seem to be different - I assumed it would end the entire load of input files, not just the current include, regardless of where in the include tree you were.  That is what I was testing in the first place.

**Comment by Southclaws** [comment]
I remember coming across this while searching for all possible directives for the pawn-parser project and assumed the same. But yeah, looking at the code they do actually just do the same thing.

I've never actually seen endscript ever get used in a library either. What were your thoughts on opening this issue? Removing it or re-using it for a different purpose? I couldn't see *much* harm in re-using it, of course we can't assume *no one* has ever used it but search-and-replace for endscript>endinput wouldn't be difficult for people.

**Comment by Y-Less** [comment]
> What were your thoughts on opening this issue? Removing it or re-using it for a different purpose?

No clue!  I'm not even sure an alternate use would be useful.

**Comment by Southclaws** [comment]
I noticed it's actually in the pdf, even though I thought I read all the directives!

> #endinput & #endscript
> Closes the current file and thereby ignores all the text below the #endinput
> directive. The directive #endscript is a synonym for #endinput.

Given that it's documented, I think it would be best not to touch it, be that re-purposing or removing.
