### ISSUE TITLE
cannot open shared object file

### ISSUE THREAD

**Issue by DuckerMan** [Southclaws/pawn#249]
Arch linux, x 64

`./pawncc`

I get error:

`./pawncc: error while loading shared libraries: libpawnc.so: cannot open shared object file: No such file or directory
`
I copyed libpawnc.so to /usr/local/lib/

**Comment by Zeex** [comment]
Does it work after you run `sudo ldconfig`?

**Comment by DuckerMan** [comment]
Wow!

Thanks!

**Comment by difaananda40** [comment]
im facing the same problem in archlinux, I already copy the bin and lib, but still got that error

**Comment by rc-bandit4461** [comment]
Steps are below. locate the lib folder inside pawnc folder, get its path, put it in LD_LIBRARY_PATH variable, export the variable and try again.
mine is located in /usr/share/pawnc-3.10.10/lib so i'll use it in the steps:

1.  `cd /usr/share/pawnc-3.10.10/lib`
2. ` export  LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH`
3. try running again

If you want to automate adding pawn lib path to LD_LIBRARY_PATH, add it to your ~/.profile or ~/.zshrc
[Source](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s)
