### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DuckerMan** [Southclaws/pawn#250]
`Pawn compiler 3.10.6	 	 	Copyright (c) 1997-2006, ITB CompuPhase

bare.pwn(1) : fatal error 100: cannot read from file: "a_samp"

Compilation aborted.

1 Error.
`

`./pawncc bare.pwn`

I want to compile default server file.

**Comment by Y-Less** [comment]
That's not an issue of the compiler, you didn't pass it any include directories.

**Comment by DuckerMan** [comment]
How i can pass it?

**Comment by Jeroen52** [comment]
pawncc "-;+" "-(+" -i:../pawno/include bare.pwn -Z -E

Op 8 jan. 2018 15:43 schreef "Sergey" <notifications@github.com>:

**Comment by Zeex** [comment]
See the output of `pawncc` without arguments, it lists all the supported command line options, among which there is `-i`.
