### ISSUE TITLE
no unsued symbol warning for references

### ISSUE THREAD

**Issue by YashasSamaga** [Southclaws/pawn#254]
```
f1(const &v) { }
f2(const ...) { }
f3(const v) { }
f4(...) { }
f5(v) { }
f6(&v) { }

main() {
	new a;
	f1(a);
	f2(a);
	f3(a);
	f4(a);
	f5(a);
	f6(a);
}
```

No unused symbol warning is triggered for `v` where it is a reference.

**Y_Less:**
> I suspect this:
> ```
> if (ident==iREFERENCE)
>       argsym->usage|=uREAD;     /* because references are passed back */
> ```
>  is a fix to prevent 204 on references, but also prevents 203 as a side-effect.

**Comment by Y-Less** [comment]
I like how you quoted my unrelated part about discord, but not the rest of the quote on the issue:

> [16:32] Y_Less: @Yashas I don't know.  I'd guess it actually has something to do with warning 204: "symbol is assigned a value that is never used", which triggers when you write a variable but never read it.
> [16:33] Y_Less: If the variable is a reference and you only write to it, there's no way to tell within that function if it is truly never read, so that is probably a fix to not generate that warning, but prevents warning 203 as well.

**Comment by YashasSamaga** [comment]
A simple fix would be to stop marking references as read and instead add a check to see if the symbol is a reference before the 204 warning is being triggered.

I am not sure if not setting the `uREAD` for references could have other side-effects.

**Comment by Y-Less** [comment]
That was exactly my thought for a simple solution too.
