### ISSUE TITLE
Jumps in assembly still don't work

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/pawn#266]
Fine:

```pawn
label:
#emit JZER label
```

Not fine:

```pawn
#emit JZER label
label:
```

Also, labels generate extra stack manipulation code.  It would be good if there was a way to do jumps without labels.  Something like this (based on `@emit`):

```pawn
#emit JZER.rel 4
```

Which generates the target address at compile-time as 4 bytes after the end of the jump op.

**Comment by Daniel-Cortez** [comment]
There's the `emit` operator which doesn't generate stack manipulation instructions (provided the label is within the `emit` block).
It's also able to make jumps to labels defined after the place of their use.
```Pawn
main()
{
	emit
	{
		jump label
label:
	}
}
```
The code above compiles into
```
00000008  proc 
0000000c  jump 00000014
00000014  zero.pri 
00000018  retn 
```
As you can see, no extra stack manipulation code.

BTW, I've made an article about the `emit` operator in Russian: http://pro-pawn.ru/showthread.php?15830
Would be great if someone could translate and upload it to the wiki (I could do some basic translation myself, but I'm not very good at it).

**Comment by Y-Less** [comment]
Ahh, that would do!  And I'll get on the translation, will be good practice.

**Comment by Daniel-Cortez** [comment]
Thanks, @Y-Less. Forgot to mention, there's also a notice at the end of the article that says reposting the text on the other forums (or any other kind of media) is not allowed - please ignore it. I guess it's only good if someone translates it into English and spreads the word.
