### ISSUE TITLE
Macro contents detection

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/pawn#50]
This:

``` pawn
#define A%0\10;%1 B
#define B%0B C

A
```

When compiled with "-l" produces "C".  My understanding of the pre-processor is that it should produce just "B"...

**Comment by Y-Less** [comment]
I played with a few methods, it is the "\10;" that causes it, somehow...  I actually saw the same bug years ago in fixes.inc, but didn't put the two together:

https://github.com/Y-Less/sa-mp-fixes/blob/90f0e9ba42f8afc7f41241bb1521058bbcf6d9b4/fixes.inc#L8128-L8140

**Comment by Y-Less** [comment]
Also possibly related:

```
#define stock%0\n;%9 stock%0 __stock$
#define iterfunc%0(%1) %0(%1) TYPES:
#define TYPES:%0$ TYPES:

stock iterfunc A(b)
{
}
```

That hangs the compiler, I don't think it should.  My expected output is:

Match *stock*:

```
stock iterfunc A(b) __stock${
}
```

Match *iterfunc*:

```
stock A(b) TYPES: __stock${
}
```

Match *TYPES*:

```
stock iterfunc A(b) TYPES:{
}
```

No matches left.  But it just hangs.

**Comment by oscar-broman** [comment]
Not sure if it helps, but this is what my macro debugger spits out:
```
SUBST(test.pwn): 5.0-20 = (28) stock iterfunc A(b) __stock$
SUBST(test.pwn): 5.6-19 = (12)  A(b) TYPES:
SUBST(test.pwn): 5.12-27 = (6) TYPES:
SUBST(test.pwn): 5.12-18 = (6) TYPES:
SUBST(test.pwn): 5.12-18 = (6) TYPES:
```

**Comment by Y-Less** [comment]
I really wanted your stepper, but it wasm't online.  Thanks - that is clearly wrong.

**Comment by oscar-broman** [comment]
Yeah sorry about that. I've been meaning to improve [this](https://github.com/oscar-broman/pawn/commit/659048855acad3fae06e0ae597872af3b7c13b21) and create a pull request here.

**Comment by Y-Less** [comment]
OK, I would love to see how much junk gets spit out using that on the YSI test script!

**Comment by Southclaws** [comment]
> When compiled with "-l" produces "C"

Could this be related to the how -l produces inaccurate results? I remember you brought it up recently.

Gonna close this with "stale" for now as it's either fixed or not a huge problem.
