### ISSUE TITLE
This compiler has random strange behavioural patterns

### ISSUE THREAD

**Issue by karimcambridge** [Southclaws/pawn#87]
What I mean is, sometimes things stop working and sometimes they start back working.

There have been one or 2 times when I compile and I get loads of errors so I'm like wtf? I compile again, boom nothing is wrong.

Besides that, look at what happened to me this month, NOTE, last few months it was working PERFECTLY fine.

`logoffDateStr = (logoffTime == 0) ? ("(Player / Server) Crash / Exit") : realdate(logoffTime);`

I've had that code for some time now, and it was working fine. Sometime this month it suddenly stopped working. It was crashing the function I was using.

`if(logoffTime == 0) {
                logoffDateStr = "(Player / Server) Crash";
            } else {
                format(logoffDateStr, 32, "%s", realdate(logoffTime));
            }` is obviously the fix.. but yea.

Full code: http://pastebin.com/2HnndWpB

What I'm trying to say is, sometimes thing just randomly go on and off! I am just reporting this, I'm not sure how much it can help you.

OS Name Microsoft Windows 10 Home
Version 10.0.10586 Build 10586
System Manufacturer LENOVO
System Model    20B2001CUS
System Type x64-based PC
System SKU  LENOVO_MT_20B2001
Processor   AMD A10-5750M APU with Radeon(tm) HD Graphics, 2500 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date   LENOVO HRET24WW (1.12), 1/24/2014
Installed Physical Memory (RAM) 16.0 GB
Total Physical Memory   15.1 GB

I guess this is related to #49? The weird thing about it is that it worked for sometime.

**Comment by Dayvison** [comment]
Yes.
I see today, the compiler sometimes I just recompile the script without change, and the amx make different results, test it:
```pawn
#include <a_samp>
#include <YSI_Data\y_iterate>
new Iterator:Stuff<500>;
main(){
	for(new i; i < 500; i ++)
	{
		Iter_Add(Stuff, i);
	}
	new tempo, id;
	
	Iter_Remove(Stuff, 499);
	id = 0;
	tempo = GetTickCount();

    printf("do-while Iter_Free=%d, %d, %d", Iter_Free(Stuff), sizeof(Iterator@Stuff), id);

	do {
	    id = random(sizeof(Iterator@Stuff));
	} while(Iter_Contains(Stuff, id));
	Iter_Add(Stuff, id);
	printf("do-while - id=%d contains=%s %dms", id, Iter_Contains(Stuff, id) ? "true" : "false", GetTickCount() - tempo);
	
	Iter_Remove(Stuff, 499);
	id = 0;
	print(" \n ");
	tempo = GetTickCount();
	
    printf("goto.... Iter_Free=%d, %d, %d", Iter_Free(Stuff), sizeof(Iterator@Stuff), id);
	Again:
    id = random(sizeof(Iterator@Stuff));
    if(Iter_Contains(Stuff, id)) goto Again;
    else
    {
        Iter_Add(Stuff, id);
    }
	printf("goto.... - id=%d contains=%s %dms", id, Iter_Contains(Stuff, id) ? "true" : "false", GetTickCount() - tempo);
}

```
Give-me sometimes the three results next:
One
```pawn
do-while Iter_Free=499, 501, 0
do-while - id=499 contains=true 3ms


goto.... Iter_Free=499, 501, 0
goto.... - id=499 contains=true 42ms
```
Two
```pawn
do-while Iter_Free=499, 501, 0
do-while - id=500 contains=false 1ms


goto.... Iter_Free=499, 501, 0
goto.... - id=500 contains=false 5ms
```
Three
```pawn
do-while Iter_Free=499, 501, 0
do-while - id=500 contains=false 3ms


goto.... Iter_Free=499, 501, 0
goto.... - id=499 contains=true 4ms
```

Windows 10
Intel Atom
4gb ram
more anything?

PS: Sorry bad english, i just learning...

**Comment by Y-Less** [comment]
You are calling `random`, of course the results are going to be different - that's the whole point of that function.

**Comment by Dayvison** [comment]
@Y-Less  but the code restricts the other values, except 499 ^^, or the code have bug, but you solved this in YSI last commit.

**Comment by staticxterm** [comment]
I noticed this too, I too had returning both literal string and string from an array (or function returning a string) using the triadic operator. Betting the problem is there somewhere.

**Comment by Y-Less** [comment]
Try this:

```pawn
new gSomeArray[5][20] = {"whatever", "you", "want", "to", "put"};
Func(a)
{
    static const RET_VAL[20] = "hi";
    return a < 5 ? gSomeArray[a] : RET_VAL;
}
```

Using a "static const" string like this actually generates code largely identical (sometimes better) than using a direct literal in the return value, and you bypass (I think) the new string literal return code.  "fixes.inc" uses `static stock const` strings for almost everything instead of literals because if you use the same string in two places, they will point to the same piece of memory, whereas if you use two identical literals, the AMX will contain two separate but identical copies of the string, because the compiler doesn't rationalise duplicates.
