### ISSUE TITLE
name collusions of local static variables in different scopes

### ISSUE THREAD

**Issue by YashasSamaga** [Southclaws/pawn#98]
I am not sure if this is really a bug. The PAWN language guide says,

> • Static local declarations A local variable is destroyed when the execution leaves the compound block in which the variable was created. Local variables in a function only exist during the run time of that function. Each new run of the function creates and initializes new local variables. When a local variable is declared with the keyword static rather than new, the variable remains in existence after the end of a function. This means that static local variables provide private, permanent storage that is accessible only from a single function (or compound block). Like global variables, static local variables can only be initialized with constant expressions.
> 
> This means that static local variables provide private, permanent storage that is accessible only from a single function (or compound block).

I don't get what is meant by "a compound block". 

```
case CUSTOM_TYPE_SHORT:
    {
        static const weps[] = {WEAPON_SHOTGUN, WEAPON_SHOTGSPA, WEAPON_SAWEDOFF};
        static const wepstr[][] = {"asdapon.", "Yoasdasdimarywadpon.", "asdasd"};

    }
    case CUSTOM_TYPE_MEDIUM:
    {
        static const weps[] = {WEAPON_M4, WEAPON_AK47};
        static const wepstr[][] = {"Youawdaweon.", "You have choseaweaw"};
    }
    case CUSTOM_TYPE_LONG:
    {
        static const weps[] = {WEAPON_RIFLE, WEAPON_SNIPER};
        static const wepstr[][] = {"You hweaweerimary waweon.", "Yowu wdvdwadary weawdpon."};
    }
```

The above code gives,

```
error 021: symbol already defined: "weps"
error 021: symbol already defined: "wepstr"
error 021: symbol already defined: "weps"
error 021: symbol already defined: "wepstr"
```

The static variables are declared in different blocks so they shouldn't trigger warnings?

EDIT:

```
case 0:
     {
         static const abc;
     }
     case 1:
     {
        static const abc;
     }
```

That doesn't give any error.

**Comment by Y-Less** [comment]
You are right on what it means by blocks - case statements SHOULD be separate blocks in which different statics can be declared, but there is a known bug in that static array names in case blocks collide.  The simple solution is to add numeric suffixes.

**Comment by Arkshine** [comment]
It might help: https://github.com/alliedmodders/amxmodx/pull/116/commits/325a746d9074d01e9869cb45b0602590f87bfb19

**Comment by YashasSamaga** [comment]
This is much more complex. The presence of a constant causes the scopes to get mangled.

```
main () {
	if(1) {
		new some_value = 4;
		const something = 3;
	}
	if(1){
		new some_value = 3;
		const something = 4;
	}
}
```

gives

```
error 021: symbol already defined: "some_value"
warning 201: redefinition of constant/macro (symbol "something")
```

```
main () {
	if(1) {
		new some_value = 4;	
	}
	if(1){
		new some_value = 3;		
	}
}
```
